// Date: 9/3/2012 8:43:24 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelProspectingTable extends ModelBase
{
  //fields
    ModelRenderer GemSmall1;
    ModelRenderer Gem1;
    ModelRenderer Gem2;
    ModelRenderer Gem3;
    ModelRenderer GemSmall2;
    ModelRenderer Shape2;
    ModelRenderer Rim1;
    ModelRenderer Rim2;
    ModelRenderer Shape1;
    ModelRenderer Rim4;
    ModelRenderer Rim3;
  
  public ModelProspectingTable()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      GemSmall1 = new ModelRenderer(this, 24, 0);
      GemSmall1.addBox(0F, 0F, 0F, 1, 1, 1);
      GemSmall1.setRotationPoint(3F, 22F, -2F);
      GemSmall1.setTextureSize(64, 32);
      GemSmall1.mirror = true;
      setRotation(GemSmall1, 0F, -0.5277876F, 0F);
      Gem1 = new ModelRenderer(this, 0, 0);
      Gem1.addBox(0F, 0F, 0F, 2, 2, 2);
      Gem1.setRotationPoint(4F, 22F, 1F);
      Gem1.setTextureSize(64, 32);
      Gem1.mirror = true;
      setRotation(Gem1, 0F, 0.3769911F, 0F);
      Gem2 = new ModelRenderer(this, 8, 0);
      Gem2.addBox(0F, 0F, 0F, 2, 2, 2);
      Gem2.setRotationPoint(0F, 22F, 1F);
      Gem2.setTextureSize(64, 32);
      Gem2.mirror = true;
      setRotation(Gem2, 0F, 0.1507964F, 0F);
      Gem3 = new ModelRenderer(this, 16, 0);
      Gem3.addBox(0F, 0F, 0F, 2, 2, 2);
      Gem3.setRotationPoint(3F, 22F, 4F);
      Gem3.setTextureSize(64, 32);
      Gem3.mirror = true;
      setRotation(Gem3, 0F, -0.4523893F, 0F);
      GemSmall2 = new ModelRenderer(this, 24, 2);
      GemSmall2.addBox(0F, 0F, 0F, 1, 1, 1);
      GemSmall2.setRotationPoint(-1F, 22F, 4F);
      GemSmall2.setTextureSize(64, 32);
      GemSmall2.mirror = true;
      setRotation(GemSmall2, 0F, -0.6283185F, 0F);
      Shape2 = new ModelRenderer(this, 0, 9);
      Shape2.addBox(0F, 0F, 0F, 1, 1, 4);
      Shape2.setRotationPoint(-4.5F, 22F, -6F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Rim1 = new ModelRenderer(this, 10, 0);
      Rim1.addBox(0F, 0F, 0F, 0, 1, 4);
      Rim1.setRotationPoint(-6F, 22F, -2F);
      Rim1.setTextureSize(64, 32);
      Rim1.mirror = true;
      setRotation(Rim1, 0F, 0F, 0F);
      Rim2 = new ModelRenderer(this, 10, 0);
      Rim2.addBox(0F, 0F, 0F, 0, 1, 4);
      Rim2.setRotationPoint(-2F, 22F, -2F);
      Rim2.setTextureSize(64, 32);
      Rim2.mirror = true;
      setRotation(Rim2, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, -4, 5);
      Shape1.addBox(0F, 0F, 0F, 4, 0, 4);
      Shape1.setRotationPoint(-6F, 22.5F, -2F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Rim4 = new ModelRenderer(this, 10, 4);
      Rim4.addBox(0F, 0F, 0F, 4, 1, 0);
      Rim4.setRotationPoint(-6F, 22F, 2F);
      Rim4.setTextureSize(64, 32);
      Rim4.mirror = true;
      setRotation(Rim4, 0F, 0F, 0F);
      Rim3 = new ModelRenderer(this, 10, 4);
      Rim3.addBox(0F, 0F, 0F, 4, 1, 0);
      Rim3.setRotationPoint(-6F, 22F, -2F);
      Rim3.setTextureSize(64, 32);
      Rim3.mirror = true;
      setRotation(Rim3, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    GemSmall1.render(f5);
    Gem1.render(f5);
    Gem2.render(f5);
    Gem3.render(f5);
    GemSmall2.render(f5);
    Shape2.render(f5);
    Rim1.render(f5);
    Rim2.render(f5);
    Shape1.render(f5);
    Rim4.render(f5);
    Rim3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
