// Date: 9/3/2012 7:02:09 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelLantern extends ModelBase
{
  //fields
    ModelRenderer Base;
    ModelRenderer Torch;
    ModelRenderer Right;
    ModelRenderer Left;
    ModelRenderer Front;
    ModelRenderer Back;
    ModelRenderer TopMiddle;
    ModelRenderer Top2;
    ModelRenderer Top1;
    ModelRenderer Handle;
  
  public ModelLantern()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Base = new ModelRenderer(this, 0, 0);
      Base.addBox(0F, 0F, 0F, 8, 1, 8);
      Base.setRotationPoint(-4F, 23F, -4F);
      Base.setTextureSize(64, 32);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      Torch = new ModelRenderer(this, 32, 9);
      Torch.addBox(0F, 0F, 0F, 2, 7, 2);
      Torch.setRotationPoint(-1F, 16F, -1F);
      Torch.setTextureSize(64, 32);
      Torch.mirror = true;
      setRotation(Torch, 0F, 0F, 0F);
      Right = new ModelRenderer(this, 32, 0);
      Right.addBox(0F, 0F, 0F, 6, 9, 0);
      Right.setRotationPoint(3F, 13.96F, 3F);
      Right.setTextureSize(64, 32);
      Right.mirror = true;
      setRotation(Right, 0F, 1.570796F, 0F);
      Left = new ModelRenderer(this, 32, 0);
      Left.addBox(0F, 0F, 0F, 6, 9, 0);
      Left.setRotationPoint(-3F, 14F, 3F);
      Left.setTextureSize(64, 32);
      Left.mirror = true;
      setRotation(Left, 0F, 1.570796F, 0F);
      Front = new ModelRenderer(this, 32, 0);
      Front.addBox(0F, 0F, 0F, 6, 9, 0);
      Front.setRotationPoint(-3F, 14F, -3F);
      Front.setTextureSize(64, 32);
      Front.mirror = true;
      setRotation(Front, 0F, 0F, 0F);
      Back = new ModelRenderer(this, 32, 0);
      Back.addBox(0F, 0F, 0F, 6, 9, 0);
      Back.setRotationPoint(-3F, 14F, 3F);
      Back.setTextureSize(64, 32);
      Back.mirror = true;
      setRotation(Back, 0F, 0F, 0F);
      TopMiddle = new ModelRenderer(this, 0, 23);
      TopMiddle.addBox(0F, 0F, 0F, 4, 2, 4);
      TopMiddle.setRotationPoint(-2F, 12F, -2F);
      TopMiddle.setTextureSize(64, 32);
      TopMiddle.mirror = true;
      setRotation(TopMiddle, 0F, 0F, 0F);
      Top2 = new ModelRenderer(this, 0, 17);
      Top2.addBox(0F, 0F, 0F, 6, 0, 6);
      Top2.setRotationPoint(-3F, 12F, -3F);
      Top2.setTextureSize(64, 32);
      Top2.mirror = true;
      setRotation(Top2, 0F, 0F, 0F);
      Top1 = new ModelRenderer(this, 0, 9);
      Top1.addBox(0F, 0F, 0F, 8, 0, 8);
      Top1.setRotationPoint(-4F, 14F, -4F);
      Top1.setTextureSize(64, 32);
      Top1.mirror = true;
      setRotation(Top1, 0F, 0F, 0F);
      Handle = new ModelRenderer(this, 24, 17);
      Handle.addBox(0F, 0F, 0F, 4, 3, 0);
      Handle.setRotationPoint(-2F, 9F, 0F);
      Handle.setTextureSize(64, 32);
      Handle.mirror = true;
      setRotation(Handle, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Base.render(f5);
    Torch.render(f5);
    Right.render(f5);
    Left.render(f5);
    Front.render(f5);
    Back.render(f5);
    TopMiddle.render(f5);
    Top2.render(f5);
    Top1.render(f5);
    Handle.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
